Initial work on textDocument/foldingRange
vlang/vls pull request #141
Opened 2021-06-30 02:10 UTC by ylluminarious

Currently, this is almost working--i.e., there are folding ranges appearing for code in the files, but the ranges aren't appearing in the right places.

Also, I created a new function in `positions.v` to ensure compatibility with appending to the `folding_ranges` variable used in `folding_range()`, because `lsp.FoldingRange` is a different type than `lsp.Range` and it has different fields.

2021-06-30 03:37 UTC, nedpals requested changes

2021-06-30 03:37 UTC, nedpals commented on vls/features.v
> +		folding_ranges << lsp_range_to_folding_range(tsrange_to_lsp_range(named_child.range()))
It's better to do the `lsp.Range` to `lsp.FoldingRange` conversion here directly instead since it's only this method that uses that consumes/uses that said function.

2021-06-30 03:37 UTC, nedpals commented on vls/positions.v
> +
Just put it directly into the `folding_range` method.

2021-06-30 06:13 UTC, ylluminarious commented on vls/features.v
> +		folding_ranges << lsp_range_to_folding_range(tsrange_to_lsp_range(named_child.range()))
@nedpals Done 👍

2021-06-30 06:13 UTC, ylluminarious commented on vls/positions.v
> +
@nedpals Done 👍

2021-06-30 08:02 UTC, nedpals approved these changes

2021-06-30 08:03 UTC, merged

2021-07-16 21:29 UTC, ylluminarious commented
@nedpals By the way, the initial issue described above is no longer happening:

> there are folding ranges appearing for code in the files, but the ranges aren't appearing in the right places.

I think I may have actually been wrong about this even not working in the first place.  This feature appears to be functioning correctly from my further usage and observation.