Implement exit and shutdown
vlang/vls pull request #27
Opened 2020-12-17 21:56 UTC by Ekopalypse

2020-12-17 22:13 UTC, Ekopalypse commented
Don't know why the general tests pass on Windows and Linux but fail on Mac

2020-12-17 23:38 UTC, JalonSolov commented
It was trying to compile `cJSON.o` and got a SIGABRT, which usually only happens if there's a critical error in a libc routine.

2020-12-17 23:48 UTC, nedpals commented
@JalonSolov I don't recommend x.json2 for now. I'll check the Linux side manually later

2020-12-18 01:56 UTC, nedpals requested changes

2020-12-18 01:56 UTC, nedpals commented on vls/general.v
> +	ls.send(json.encode(result))
If this is the case, I would suggest to have a pre-encoded JSON response instead of encoding it in real time.

2020-12-18 01:56 UTC, nedpals commented on vls/general.v
> +	ls.send(json.encode(result))
The `params` param isn't needed as well so you can omit that one.

2020-12-18 01:56 UTC, nedpals commented on vls/general.v
> +	ls.send(json.encode(result))
Make sure to add a test as well.

2020-12-18 09:57 UTC, danieldaeschle commented on vls/general.v
> +	ls.send(json.encode(result))
Why do we need a response here? If we need, why not using JrpcReponse?

2020-12-18 09:57 UTC, danieldaeschle commented
You need to resolve conflicts

2020-12-18 11:44 UTC, Ekopalypse commented on vls/general.v
> +	ls.send(json.encode(result))
Correct, param is not needed here.

[Shutdown](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#shutdown) is a request, hence the need for a response, unlike exit which is a notification. JrpcResponse defines a generic structure as input, which is not present in this case. I seem to have misunderstood something, can JrpcResponse be used without passing a concrete structure?

Regarding the exit test, I had already thought about it but have not yet come up with a sensible solution on how to test the termination of the process in the existing test environment. Ideas?

2020-12-18 11:50 UTC, Ekopalypse commented on vls/general.v
> +	ls.send(json.encode(result))
Concerning the exit-test, what about using ServerStatus off here and checking the status?

2020-12-18 12:09 UTC, danieldaeschle commented on vls/general.v
> +	ls.send(json.encode(result))
just pass string as generic parameter.

2020-12-18 12:10 UTC, danieldaeschle commented on vls/general.v
> +	ls.send(json.encode(result))
> Concerning the exit-test, what about using ServerStatus off here and checking the status?

you can do that, but what about the exit?
such cases should be tested with an regression testing client. we don't have it currently.

2020-12-18 12:32 UTC, Ekopalypse commented on vls/general.v
> +	ls.send(json.encode(result))
Sorry, I forgot to reply to "_precoded JSON response_".
My understanding is that a null response must be sent for each request that is not otherwise processed by the LSP server.
Would mean that there are several such pre-encoded responses in the module.
Could be ok as long as MS does not add something to a null response, wondering what that would be?

2020-12-18 13:13 UTC, nedpals commented on vls/general.v
> +	ls.send(json.encode(result))
> My understanding is that a null response must be sent for each request that is not otherwise processed by the LSP server.
Based from what I've read and understood, this is true.

> Would mean that there are several such pre-encoded responses in the module.
What do you mean by this? If the pre-encoded response you're referring to is the same across the module, it would make sense to spin it off as a separate function (`null_response(id int)` in this) instead.

> Could be ok as long as MS does not add something to a null response, wondering what that would be?
As long as you included the ID of the request you want to respond, I believe the client would know the context of it. MS wouldn't have any modifications to it since they're strictly following the JSON-RPC standard

2020-12-18 13:53 UTC, Ekopalypse commented on vls/general.v
> +	ls.send(json.encode(result))
> What do you mean by this? If the pre-encoded response you're referring to is the same across the module, it would make sense to spin it off as a separate function (`null_response(id int)` in this) instead.

I think that probably no server implementation can functionally map all possible lsp requests and therefore must return a null response for several requests.
My understanding of the current code base tells me that this can either be done in the individual requests.v files, such as definition.v or declaration.v, or possibly 
in the else branch of the execute function of the vls.v file.
Check that this is a request and not a notification and then send a null_response.
This seems to be the most sensible solution at the moment, unless I am missing something.

2020-12-18 13:57 UTC, danieldaeschle commented on vls/general.v
> +	ls.send(json.encode(result))
We don't need a null Response, just use a proper response instead with a string as generic parameter.

2020-12-18 14:00 UTC, Ekopalypse commented on vls/general.v
> +	ls.send(json.encode(result))
> We don't need a null Response, just use a proper response with a string as generic parameter instead.

Sorry, it was not my intention to give the impression that we need a zero response structure. I use the term to illustrate that this response must be made.

2020-12-18 14:11 UTC, danieldaeschle commented on vls/general.v
> +	ls.send(json.encode(result))
Yeah, just change it and it's ok :)
Thanks for that hint

2020-12-18 15:43 UTC, closed without merging

2020-12-18 16:05 UTC, danieldaeschle commented
Why closed?

2020-12-18 16:09 UTC, Ekopalypse commented
Because of the conflicts. It looks like it easier to sync and recreate the PR then to try to resolve the conflicts