vls: implement textDocument/didClose
vlang/vls pull request #29
Opened 2020-12-18 13:51 UTC by nedpals

Includes simplifications in formatting feature as well as making Document URIs the standard map keys in some of the fields

2020-12-18 14:08 UTC, danieldaeschle requested changes

2020-12-18 14:08 UTC, danieldaeschle commented on vls/vls.v
>  fn (mut ls Vls) insert_files(files []ast.File) {
could you document this function? i don't know exactly what it does.

2020-12-18 14:08 UTC, danieldaeschle commented on vls/text_synchronization.v
> +	// clear diagnostics
Do we want to clear diagnostics on closed files? I would like to have errors on closed files as well.

2020-12-18 14:08 UTC, danieldaeschle commented on vls/text_synchronization.v
> +	if target_dir_uri in ls.tables {
that's the thing i didn't get out of this function. In my opinion it shouldn't be any file state modification there. is it possible to move it out?

2020-12-19 01:26 UTC, nedpals commented on vls/text_synchronization.v
> +	if target_dir_uri in ls.tables {
i'll create a separate function for it so we can distinguish the diagnostics part to the file modification

2020-12-19 01:30 UTC, nedpals commented on vls/text_synchronization.v
> +	// clear diagnostics
I think yes. There are instances where a user will accidentally open a file which the user didn't intend to (or opened from a path outside the workspace) and it will be frustrating if they're not cleared on close.

I'll just add conditions to this. The diagnostics will be cleared if:
- If a workspace has opened multiple programs with `main()` function and one of them is closed.
- If a file opened is outside the root path or workspace.
- If there are no remaining files opened on a specific folder.

These are all I can think of right now. What do you think?

2020-12-19 01:32 UTC, nedpals commented on vls/vls.v
>  fn (mut ls Vls) insert_files(files []ast.File) {
Noted

2020-12-19 02:13 UTC, nedpals commented on vls/text_synchronization.v
> +	if target_dir_uri in ls.tables {
@danieldaeschle I've updated it. Please take a look.

2020-12-19 08:04 UTC, danieldaeschle approved these changes
Im on phone right now. Can't see it properly. But i saw you outsource it. I trust you ;)

2020-12-19 08:05 UTC, merged