Implement CLI, add ability to disable/enable feature flags
vlang/vls pull request #32
Opened 2020-12-19 04:23 UTC by nedpals

This PR should re-run the job CI and merged after https://github.com/vlang/v/pull/7405 has been merged.

2020-12-19 08:45 UTC, danieldaeschle commented on cmd/vls/main.v
> +import cli
whoo. did i missed something? never saw that module. nice :)

2020-12-19 08:49 UTC, danieldaeschle requested changes

2020-12-19 08:49 UTC, danieldaeschle commented on vls/diagnostics.v
> +	if !ls.enabled_features['diagnostics'] { return }
for what do we need this?

2020-12-19 08:49 UTC, danieldaeschle commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, state bool) ? {
can't we set features in `new`? instead of having a new method.

2020-12-19 08:49 UTC, nedpals commented on cmd/vls/main.v
> +import cli
I never understood why there's are overlapping modules for this purpose on vlib (looking at you `flag`) but yeah it was nice.

2020-12-19 08:56 UTC, nedpals commented on vls/diagnostics.v
> +	if !ls.enabled_features['diagnostics'] { return }
To make it easier to enable/disable features for debugging without commenting and rebuilding or if the user doesn't want it (by just adjusting the extension settings or workspace-specific config). It will also be a great way to ship and enable experimental features if the user wants to take a risk

2020-12-19 09:03 UTC, nedpals commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, state bool) ? {
For the sake of CLI yes, but for other purposes (like testing) it's a nope.

2020-12-19 09:04 UTC, danieldaeschle commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, state bool) ? {
why it's not possible in testing?

2020-12-19 09:04 UTC, danieldaeschle commented on vls/vls.v
> +	features_list = [
Can you use an enum?

2020-12-19 09:05 UTC, danieldaeschle commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, state bool) ? {
I mean having a parameter in the `new` function. Then you can set it in the tests as well.

2020-12-19 09:21 UTC, nedpals commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, state bool) ? {
> I mean having a parameter in the new function. Then you can set it in the tests as well.

If it's going to a parameter in `new`, it should be a vararg instead like `new(features_to_enable ...string)` but since it's still not possible to spread arrays into it, I think this is better for now. 

There's also an idea to use `[]string` for it in the meantime like `new(features_to_enable []string)` but it's also pointless to do `new(['*'])` most of the time. Enabling/disabling these is a CLI thing

2020-12-19 09:28 UTC, danieldaeschle commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, state bool) ? {
ok

2020-12-19 09:34 UTC, nedpals commented on vls/vls.v
> +	features_list = [
That was my first idea but I kinda missing something so I'll try to reevaluate and change this to enum-based

2020-12-21 20:11 UTC, danieldaeschle requested changes

2020-12-21 20:11 UTC, danieldaeschle commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, enable bool) ? {
Why not use an enum list here as parameter as well?

2020-12-21 20:11 UTC, danieldaeschle commented on vls/vls.v
> +	return ls.enabled_features.map(it.str())
Why not return list of enums?

2020-12-22 05:05 UTC, nedpals commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, enable bool) ? {
Because we're passing the parameter data from the CLI to here. Besides, if the said feature in string isn't available, the function will complain and thus be passed to the CLI

2020-12-22 05:05 UTC, nedpals commented on vls/vls.v
> +	return ls.enabled_features.map(it.str())
I'll be changing this. Thanks.

2020-12-22 07:39 UTC, danieldaeschle commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, enable bool) ? {
hmmm

2020-12-22 07:40 UTC, danieldaeschle commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, enable bool) ? {
the api shouldn't be related to a use case like the cli... could you do the `feature_from_string` in the cli instead of set_features?

2021-01-09 07:19 UTC, nedpals commented on vls/vls.v
> +pub fn (mut ls Vls) set_features(features []string, enable bool) ? {
@danieldaeschle would you like to expose the `.features` field then?

2021-01-10 03:33 UTC, nedpals commented
It's not the best implementation yet but we can improve it later. Urgently merge this in order for https://github.com/vlang/vls/pull/34 to be merged

2021-01-10 03:33 UTC, merged