vls: implement textDocument/completion
vlang/vls pull request #34
Opened 2020-12-21 04:20 UTC by nedpals

2020-12-21 20:17 UTC, danieldaeschle commented on cmd/vls/stdio.v
> +	unsafe {buf.free()}
The heck?

2020-12-21 20:22 UTC, danieldaeschle commented on vls/text_synchronization.v
> +		uri.str().free()
Is this a hack?

2020-12-21 20:23 UTC, danieldaeschle commented on vls/features.v
> +fn (mut ls Vls) formatting(id int, params string) {
Why mut?

2020-12-21 20:24 UTC, danieldaeschle commented on vls/ast.v
> +module vls
we will merge that into v itself, right?

2020-12-21 22:26 UTC, StunxFS commented on cmd/vls/stdio.v
> +}
Especially when a match is formatted, it leaves it somewhat ugly, that you have to accommodate everything manually.

2020-12-21 23:44 UTC, nedpals commented on vls/features.v
> +fn (mut ls Vls) formatting(id int, params string) {
my bad 😂

2020-12-21 23:46 UTC, nedpals commented on vls/text_synchronization.v
> +		uri.str().free()
no really. im looking to find ways to free  memory but ill somewhat remove it later since it only frees little memory

2020-12-22 07:36 UTC, danieldaeschle commented on cmd/vls/stdio.v
> +}
Yeah, but your issue is not related to this.

2020-12-22 07:37 UTC, danieldaeschle commented on vls/text_synchronization.v
> +		uri.str().free()
because you creating a string and free it immediately.

2020-12-23 18:03 UTC, danieldaeschle commented on jsonrpc/jsonrpc.v
> +struct Response2 <T> {
nah, hacky workaround. but the json module still doesn't support it, right?

2020-12-23 18:08 UTC, danieldaeschle commented on vls/completion.v
> +fn (ls Vls) completion_item_stmt(stmt ast.Stmt, mut completion_items []lsp.CompletionItem, cfg CompletionItemConfig) {
I have problems figure out what does function does. Name name is confusing. Could you rethink the name? Maybe a comment does it as well. But the name should be clear in first place.

2020-12-23 18:11 UTC, danieldaeschle commented on vls/completion.v
> +fn (ls Vls) completion_item_stmt(stmt ast.Stmt, mut completion_items []lsp.CompletionItem, cfg CompletionItemConfig) {
After reading it it sounds like it creates completion item from a stmt. But it's not only one. What about `completion_items_from_stmt`?
Can you make this method pure? to return the `completion_items` instead of modifying it?

2020-12-23 18:12 UTC, danieldaeschle commented on vls/completion.v
> +	// TODO: Support more nodes.
Could you create a list of nodes which needs to be supported in the PR? To see the progress...

2020-12-23 18:12 UTC, danieldaeschle commented on vls/completion.v
> +	mut expr_typ := 0
`table.Type(0)`

2020-12-23 18:13 UTC, danieldaeschle commented on vls/completion.v
> +	match expr {
Not sure if you want to add more branches. But an if is does fit as well.

2020-12-23 18:15 UTC, danieldaeschle commented on vls/completion.v
> +		if typ_name.starts_with('[]') {
this checks can be done more elegant using the `typ_sym.kind`.

Can you rename it to `type_sym`? It's more common in the compiler. `typ` is only used if `type` doesn't work.

2020-12-23 18:16 UTC, danieldaeschle commented on vls/completion.v
> +				insert_text: '${m.name}()'
Is it possible to add parameter placeholders and some markers to jump with `<TAB>`?

2020-12-23 18:17 UTC, danieldaeschle commented on vls/completion.v
> +			ls.completion_item_stmt(stmt, mut completion_items, {
Here something like `completion_items << ls.completion_item_stmt()`

2020-12-23 18:18 UTC, danieldaeschle commented on vls/completion.v
> +	offset := raw_offset - 4
What does this mean?

2020-12-23 18:20 UTC, danieldaeschle commented on vls/completion.v
> +		// invoked through typing and through control+enter. my idea
for me it's Ctrl+Space, did you mean that?

2020-12-23 18:21 UTC, danieldaeschle commented on vls/completion.v
> +		// again but uses local variables which sounds dumb.
not sure what you mean :/
read it 3 times now.

2020-12-23 18:22 UTC, danieldaeschle commented on vls/completion.v
> +		node := ls.get_ast_by_pos(pos.line, pos.character - 2, src.bytestr(), file.stmts.map(AstNode(it))) or {
tbh: this is awesome :)
💯

2020-12-23 18:24 UTC, danieldaeschle commented on vls/completion.v
> +			ls.log_message('ast node not found... sending cached one', .info)
cached ones are sent if the user pressed ctrl+space without having any node on the left?
shouldn't it send all values, globals and function names? why are you sure the cache has them?

isn't it possible to get them without using the cache?

2020-12-23 18:27 UTC, danieldaeschle commented on vls/completion.v
> +		if ctx.trigger_character == '.' {
not that important right now. but having an enum or some globals for trigger characters would be helpful.

2020-12-23 18:33 UTC, danieldaeschle commented on vls/completion.v
> +		ls.cached_completion = completion_items.clone()
so, basically it's just the last calculated completion. If i see it correctly it only fit's to the same trigger/node. It shouldn't be used in other contexts.

2020-12-23 18:38 UTC, danieldaeschle commented on vls/vls.v
> +fn (mut ls Vls) extract_symbols(parsed_files []ast.File, table &table.Table, pub_only bool) {
should that be in vls.v? In which context is this needed? autocompletetion? then move it to autocomplete maybe.

2020-12-23 23:59 UTC, nedpals commented on jsonrpc/jsonrpc.v
> +struct Response2 <T> {
ill remove this once i implemented `omitempty` on JSON later

2020-12-24 00:00 UTC, nedpals commented on vls/completion.v
> +fn (ls Vls) completion_item_stmt(stmt ast.Stmt, mut completion_items []lsp.CompletionItem, cfg CompletionItemConfig) {
noted 👍👍

2020-12-24 00:00 UTC, nedpals commented on vls/completion.v
> +	// TODO: Support more nodes.
ill be updating the PR description today

2020-12-24 00:02 UTC, nedpals commented on vls/completion.v
> +		if typ_name.starts_with('[]') {
i thought there would be some flag check similar to generics.

ill rename them later. got used to `typ` bc of the keyword problem 😂

2020-12-24 00:03 UTC, nedpals commented on vls/completion.v
> +				insert_text: '${m.name}()'
it should be. ill search my old vscode-vlang fork for this code

2020-12-24 00:05 UTC, nedpals commented on vls/vls.v
> +fn (mut ls Vls) extract_symbols(parsed_files []ast.File, table &table.Table, pub_only bool) {
noted 👍

2020-12-24 06:43 UTC, nedpals commented on vls/completion.v
> +	offset := raw_offset - 4
removed

2020-12-24 07:15 UTC, nedpals commented on vls/completion.v
> +			ls.log_message('ast node not found... sending cached one', .info)
I have removed the cache as it is not needed anymore

2020-12-24 07:15 UTC, nedpals commented on vls/completion.v
> +	// TODO: Support more nodes.
Updated the PR description

2020-12-24 08:41 UTC, danieldaeschle commented on vls/completion.v
> +	// TODO: Support more nodes.
I will investigate abou that parser error

2020-12-24 08:42 UTC, danieldaeschle commented on vls/completion.v
> +		if typ_name.starts_with('[]') {
Didn't get your first sentence. It should be possible to use kind, right?

2020-12-24 09:05 UTC, danieldaeschle requested changes

2020-12-24 09:05 UTC, danieldaeschle commented on vls/completion.v
> +fn (ls Vls) completion_item_from_stmt(stmt ast.Stmt, cfg CompletionItemConfig) []lsp.CompletionItem {
`completion_items_from_stmt`

2020-12-24 09:05 UTC, danieldaeschle commented on vls/completion.v
> +fn (ls Vls) completion_item_from_expr(expr ast.Expr, cfg CompletionItemConfig) []lsp.CompletionItem {
`completions_item_from_expr`

2020-12-24 09:05 UTC, danieldaeschle commented on vls/completion.v
> +fn (ls Vls) completion_item_from_fn(fnn table.Fn, is_method bool) lsp.CompletionItem {
`completion_items_from_fn`

2020-12-24 09:05 UTC, danieldaeschle commented on vls/completion.v
> +fn (ls Vls) completion_item_from_type_info(type_info table.TypeInfo) []lsp.CompletionItem {
`completion_items_from_type_info`

2020-12-24 09:05 UTC, danieldaeschle commented on vls/completion.v
> +	} else if ctx.trigger_kind == .invoked && (offset - 1 >= 0 && src[offset - 1] == ` `) {
Could you comment this?

2020-12-24 09:30 UTC, nedpals commented on vls/completion.v
> +	} else if ctx.trigger_kind == .invoked && (offset - 1 >= 0 && src[offset - 1] == ` `) {
will do :+1:

2020-12-28 09:02 UTC, nedpals commented on vls/completion.v
> +					ls.completion_items_from_stmt(node, cfg)
I decided to use a single config in case some method inside that method needs a spcific data for example

2020-12-28 09:03 UTC, nedpals commented on vls/vls.v
> +	invalid_imports map[string][]string
Not yet. If you have an idea/suggestion, feel free to leave it here :smiley:

2020-12-28 17:50 UTC, danieldaeschle commented on vls/completion.v
> +		if ctx.trigger_character == '.' && (offset - 1 >= 0 && src[offset - 1] != ` `) {
Can you document what this offeset - 1 >= 0 && src[offset - 1] != \` ` means?

2020-12-28 17:50 UTC, danieldaeschle commented on vls/vls.v
> +	invalid_imports map[string][]string
Can you document the purpose of caching invalid imports?

2020-12-28 17:50 UTC, danieldaeschle commented on vls/completion.v
> +					ls.completion_items_from_stmt(node, cfg)
hmm, get's more complicated then, or? leave it for now.

2020-12-28 22:59 UTC, nedpals commented on vls/vls.v
> +	invalid_imports map[string][]string
sure thing

2020-12-28 22:59 UTC, nedpals commented on vls/completion.v
> +		if ctx.trigger_character == '.' && (offset - 1 >= 0 && src[offset - 1] != ` `) {
yep will do

2020-12-29 00:02 UTC, danieldaeschle commented
this PR is so big xD

2020-12-29 00:06 UTC, JalonSolov commented
As long as it's between you 2, you get to decide when "big" is "too big".

In general, it's better to do several smaller PRs, so they're quicker & easier to review.

However, sometimes it just needs a big PR to get the important stuff done together.

2020-12-29 01:25 UTC, nedpals commented
> As long as it's between you 2, you get to decide when "big" is "too big".
> 
> In general, it's better to do several smaller PRs, so they're quicker & easier to review.
> 
> However, sometimes it just needs a big PR to get the important stuff done together.

True. However for transparency and quality control (since users are now using the language server), I generally tend to spin off some of the final code from here into smaller PRs and let @danieldaeschle review them. For example, PR's #38 #39 #40 (and the previous ones I can't remember) were all came from here and it's a better system to me atleast

2020-12-29 02:58 UTC, JalonSolov commented
Whatever works best for you is fine by me.  :-)

2020-12-30 18:42 UTC, danieldaeschle commented on vls/completion.v
> +	{
why extra scope?

2020-12-30 18:45 UTC, danieldaeschle commented
good job so far. if you finished your todos i will checkout your code, test it and read the code.

2021-01-06 11:43 UTC, danieldaeschle commented on vls/completion.v
> +	show_only_global_fn bool
vfmt ;)

2021-01-06 11:45 UTC, danieldaeschle commented on vls/features.v
> +fn (mut ls Vls) document_symbol(id int, params string) {
why mut?

2021-01-06 12:41 UTC, nedpals commented on vls/completion.v
> +	show_only_global_fn bool
surprisingly doesn't format it after a couple of time :///

2021-01-06 12:43 UTC, nedpals commented on vls/features.v
> +fn (mut ls Vls) document_symbol(id int, params string) {
the generated symbols are cached immediately so it can still be displayed even if there are parser errors. see `generate_symbols` method

2021-01-06 12:49 UTC, danieldaeschle commented on vls/features.v
> +fn (mut ls Vls) document_symbol(id int, params string) {
ah, didn't see Vls is modified.

2021-01-06 12:49 UTC, danieldaeschle commented on vls/completion.v
> +	show_only_global_fn bool
lol :D

2021-01-06 12:51 UTC, danieldaeschle commented
Can you explain [3]? Maybe I can implement it.

2021-01-06 14:09 UTC, nedpals commented on vls/completion.v
> +	// See L277-L284 for the `mut` reason.
Will replace this line

2021-01-06 14:09 UTC, nedpals commented on vls/completion.v
> +	file_imports        []string   // for displaying module symbols or module list
Can't figure out what's the issue with vfmt here not formatting this properly

2021-01-06 15:38 UTC, nedpals commented
> Can you explain [3]? Maybe I can implement it.

It's good now. It's part of #7715 as well so it can use the AST walker to detect the import statment 😃 I'll update the description

2021-01-07 07:46 UTC, danieldaeschle commented on vls/completion.v
> +	show_global         bool 			 = true // for displaying global (project) symbols
:D

2021-01-07 07:48 UTC, danieldaeschle commented on vls/completion.v
>  	for sym_name, idx in cfg.table.type_idxs {
create a extra function for this: `get_type_symbol_starts_with`

2021-01-07 07:59 UTC, nedpals commented on vls/completion.v
>  	for sym_name, idx in cfg.table.type_idxs {
it's unnecessary for now. i'll extract it later if there's any similar code that uses it but ill be adding a comment for clarity

2021-01-10 05:28 UTC, merged