api: migrate the reader API
vlang/vls pull request #373
Opened 2022-07-27 19:21 UTC by vincenzopalazzo

Start to migrate to the new read API https://github.com/vlang/v/pull/15229

This is a work in progress, and I think there are some things wrong with the tests, but let's start to run the same things

2022-07-28 10:09 UTC, nedpals commented on test_utils/test_utils.v
> +	}) or { return none }
That's weird. Do you get compiler errors in this?

2022-07-28 10:15 UTC, vincenzopalazzo commented on test_utils/test_utils.v
> +	}) or { return none }
In my local machine no, but I see that the result of the CI is totally different, I need to take a look inside it

2022-07-28 10:15 UTC, nedpals commented on server/general_test.v
> +	}) or { return err }
Same comment with `test_utils/test_utils.v`

2022-07-28 10:15 UTC, nedpals commented on server/general_test.v
> +		return err
Same comment with `test_utils/test_utils.v`

2022-07-28 10:18 UTC, nedpals reviewed
Other than the relevant ones (streams.v, jsonrpc), the rest should probably be discarded as they're just irrelevant in the change

2022-07-28 21:44 UTC, vincenzopalazzo commented on test_utils/test_utils.v
> +	}) or { return none }
ok! with the PR https://github.com/vlang/v/pull/15229 I received 


```
gitpod /workspace/vls (macros/reader_migration) $ v run build.vsh clang
> Building VLS...
v -g -gc boehm -d use_libbacktrace -cc clang cmd/vls -o /workspace/vls/bin/vls
> VLS built successfully!
Executable saved in: /workspace/vls/bin/vls
gitpod /workspace/vls (macros/reader_migration) $ 

```

2022-07-28 21:44 UTC, vincenzopalazzo commented on server/general_test.v
> +	}) or { return err }
https://github.com/vlang/vls/pull/373#discussion_r932704141

2022-07-28 21:44 UTC, vincenzopalazzo commented on server/general_test.v
> +		return err
https://github.com/vlang/vls/pull/373#discussion_r932704141

2022-07-28 21:46 UTC, vincenzopalazzo commented
>Other than the relevant ones (streams.v, jsonrpc), the rest should probably be discarded as they're just irrelevant in the change

We do not use the `v fmt` in this repo?

In addition, I'm interested on why the test is failing, because to me takes a while and maybe you can find with just check the diff?

My `v test .`

```
 OK    [30/30] 11288.124 ms /workspace/vls/cmd/vls/connection_test.v
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Failed command 1:    '/workspace/v/v'   -o '/tmp/v/test_session_129349957687745/server_test' '/workspace/vls/jsonrpc/server_test.v'
Failed command 2:    '/workspace/v/v'   -o '/tmp/v/test_session_129349957687745/general_test' '/workspace/vls/server/general_test.v'
Failed command 3:    '/workspace/v/v'   -o '/tmp/v/test_session_129349957687745/completion_test' '/workspace/vls/server/tests/completion_test.v'
Summary for all V _test.v files: 3 failed, 27 passed, 30 total. Runtime: 11289 ms, on 15 parallel jobs.

```

2022-07-29 02:09 UTC, nedpals commented
> We do not use the v fmt in this repo?

Not yet (see: https://github.com/vlang/vls/pull/352#pullrequestreview-1016787030) . Also just to avoid unnecessary stuff when "blame"ing/blaming the file.

> In addition, I'm interested on why the test is failing, because to me takes a while and maybe you can find with just check the diff?
>
> My v test .

Hmm. I'll take a lok

2022-07-29 02:58 UTC, nedpals requested changes
Most of the test you've mentioned fails is because the change you made for `TestClient.send<T>` now returns a result which is not appropriate since JSON-RPC responses might return nulls. 

Basically you can just revert most of the code but only keep the relevant portions where there are `read` methods or the `read` method is called.

2022-07-29 02:58 UTC, nedpals commented on jsonrpc/server_test_utils/server_test_utils.v
> +pub fn (mut tc TestClient) send<T, U>(method string, params T) !U {
Regarding the failed test in `jsonrpc/server_test.v`, this should be reverted since JSONRPC responses can return nulls (aka `none`)

2022-07-29 02:58 UTC, nedpals commented on jsonrpc/server_test_utils/server_test_utils.v
> +	tc.server.respond() or { return IError(io.Eof{}) }
Revert this or the `jsonrpc/server_test` might not catch server errors (like `method not found` and etc.)

2022-07-29 02:58 UTC, nedpals commented on jsonrpc/server_test_utils/server_test_utils.v
> +		return IError(io.Eof{})
Also revert this one (we use `none` for `null` results)

2022-07-29 02:58 UTC, nedpals commented on jsonrpc/server_test_utils/server_test_utils.v
>  	}
We cannot see the real error when decoding `json` so this should also be reverted.

2022-07-29 02:58 UTC, nedpals commented on server/general_test.v
revert this one

2022-07-29 02:58 UTC, nedpals commented on server/general_test.v
> +	}) or { return err }
Also revert this

2022-07-29 02:58 UTC, nedpals commented on server/general_test.v
> +		return err
Revert this one

2022-07-29 02:58 UTC, nedpals commented on test_utils/test_utils.v
> +	}) or { return none }
I see. You can just revert this one back since i suggested that the `TestClient.send` should be an optional

2022-07-29 02:58 UTC, nedpals commented on jsonrpc/server_test.v
> +	hello_result := client.send<string, RpcResult<string>>('hello', '') or { return err }
Revert this

2022-07-29 09:29 UTC, vincenzopalazzo commented on jsonrpc/server_test_utils/server_test_utils.v
> +pub fn (mut tc TestClient) send<T, U>(method string, params T) !U {
we cannot reverted it because the interface is changed now inside the API, we need to return `io.Eof` instead of null

2022-07-29 09:30 UTC, vincenzopalazzo commented on jsonrpc/server_test_utils/server_test_utils.v
> +		return IError(io.Eof{})
we can use `none` with the new interface? or we should change the code to reflex the new interface?

I think the second, right?

2022-07-29 09:31 UTC, vincenzopalazzo commented on jsonrpc/server_test_utils/server_test_utils.v
>  	}
I think we can, we need just check if it is returned `io.Eof`

2022-07-29 09:31 UTC, vincenzopalazzo commented on server/general_test.v
we can't!

2022-07-29 09:31 UTC, vincenzopalazzo commented on jsonrpc/server_test.v
> +	hello_result := client.send<string, RpcResult<string>>('hello', '') or { return err }
same, we can't

2022-07-29 09:35 UTC, vincenzopalazzo commented
>Most of the test you've mentioned fails is because the change you made for TestClient.send<T> now returns a result which is not appropriate since JSON-RPC responses might return nulls.

The reason for this PR is just that we are changing the `send`, and I just ask if you can point me in the right direction just to understand when and why this test is failing.

But looks like that we are not converging to nothing useful so I will make ready this PR with all the trivial change that required to be conformed to the new API

Thanks!

2022-07-29 22:01 UTC, closed without merging