Hover message improvement
vlang/vls pull request #424
Opened 2023-01-28 10:24 UTC by SirZenith

Add more detailed information into hover doc (for imports, variables).

I think hover feature is now large enough to have its own file.

Though it might seems to have to much information in hover message, please bear with it for now. This can make symbol registration debugging easier, an feature switch can be added later if needed.

2023-01-29 14:38 UTC, SirZenith commented
Spot a bug in `structures/ropes/ropes.v`. Rope uses `[]rune` for storing content, while everywhere else is indexing into content with byte index.

This cause problem when source code contains characters which takes more than one byte, OR when source code uses encoding other than UTF-8.

Gonna fix it here, since it's vital to other things in this PR.

2023-02-01 16:44 UTC, spytheman commented on analyzer/imports.v
> +}
Excellent idea, returning several bools is indeed very confusing.

2023-02-01 16:47 UTC, spytheman commented on analyzer/imports.v
> +		mut path_segments := []string{len: mod_names.len, cap: mod_names.len}
```suggestion
		mut path_segments := []string{len: mod_names.len}
```
is enough since .cap is set automatically based on .len, so cap is needed only in situations that you know that the array will grow in advance and its final size, to avoid reallocations.

2023-02-01 16:49 UTC, spytheman commented on analyzer/symbol.v
> +// get_type_def_keyworkd return keyword corressponding to type definition used by
```suggestion
// get_type_def_keyword returns a keyword corresponding to type definition used by
```

2023-02-01 16:50 UTC, spytheman commented on analyzer/symbol.v
> +// is_type check if a symbol defines a type (struct, enum, etc.).
```suggestion
// is_type_defining_kind checks if a symbol defines a type (struct, enum, etc.).
```

2023-02-01 16:54 UTC, spytheman commented on server/features_hover.v
> +	}
why is it difficult?

2023-02-01 16:55 UTC, spytheman commented on server/features_hover.v
> +	}
please put the reason in the comments, and may be a TODO: too, so that it could be re-evaluated in time

2023-02-01 16:57 UTC, spytheman requested changes
Good work.

2023-02-01 17:37 UTC, SirZenith commented on server/features_hover.v
> +	}
Done.

2023-02-02 00:55 UTC, SirZenith commented
Module name hover doc now has proper test case.

2023-02-02 10:10 UTC, spytheman commented
Excellent!

2023-02-02 10:10 UTC, merged