vls: implement textDocument/signatureHelp
vlang/vls pull request #55
Opened 2021-01-10 05:54 UTC by nedpals

Add support for signature help as a companion of autocompletion feature

2021-02-18 13:57 UTC, nedpals commented on lsp/signature_help.v
> +	// extend: TextDocumentPositionParams
it's supposed to be "embed" and I commented it back when struct embedding is broken (i'll add a TODO message for this since I want to utilize struct embedding)

2021-02-18 20:40 UTC, danieldaeschle commented
conflicts and failing CI then i will review and approve it

2021-02-18 20:44 UTC, danieldaeschle requested changes

2021-02-18 20:44 UTC, danieldaeschle commented on lsp/signature_help.v
> +	trigger_character     string									 [json: triggerCharacter]
please fix it

2021-02-18 20:44 UTC, danieldaeschle commented on lsp/signature_help.v
> +	// active_signature int                    [json: activeSignature]
remove commented code or add a comment

2021-02-18 20:44 UTC, danieldaeschle commented on lsp/signature_help.v
> +	// document string
remove it

2021-02-19 11:45 UTC, nedpals commented
> conflicts and failing CI then i will review and approve it

I added a temporary solution in the meantime because of the problem surrounding `strings.Builder` string output on MSVC.

2021-02-24 17:56 UTC, danieldaeschle requested changes

2021-02-24 17:56 UTC, danieldaeschle commented on vls/features.v
> +			mut sb := ''
It's not a string builder. Can you name the variable what it is for?

2021-02-26 03:51 UTC, nedpals commented on vls/features.v
> +			mut sb := ''
Will do

2021-02-27 19:58 UTC, danieldaeschle approved these changes

2021-02-27 19:58 UTC, merged