vls: implement textDocument/hover
vlang/vls pull request #58
Opened 2021-01-12 08:38 UTC by nedpals

Implements the hover feature.

# Roadmap
WIP

2021-02-10 10:32 UTC, danieldaeschle requested changes

2021-02-10 13:28 UTC, nedpals commented on vls/tests/hover_test.v
> +		return
nah it still shows the error (im running on the latest version of V):
![image](https://user-images.githubusercontent.com/7358345/107516121-e98e4f80-6be6-11eb-83d2-9d0be1edf036.png)

2021-02-10 13:28 UTC, nedpals commented on vls/features.v
> +	src									[]byte
nop. i haven't formatted the code yet that's why

2021-02-10 13:30 UTC, nedpals commented on lsp/hover.v
> +// pub type MarkedString = string | MarkedString
i fixed a typographical error that appeared on the master branch (idk why it had the big letter S on it)

2021-02-10 13:32 UTC, nedpals commented on vls/ast.v
>  			node_pos := node.position()
the `data` variable is mutable because thats where the inspector will store the node if it passes the criteria below (see line 21 and 26)

2021-02-16 10:36 UTC, danieldaeschle commented on vls/ast.v
>  			node_pos := node.position()
i mean: isn't it needed to do this: `walker.inspect(node, mut data, fn ...` ?

2021-02-18 10:47 UTC, nedpals commented on vls/ast.v
>  			node_pos := node.position()
you're right. it took me a while to understand it :laughing: i thought you were referring to the callback function which had a `mut` keyword on the `data` already. i'll fix this

2021-02-18 11:31 UTC, nedpals commented on vls/ast.v
>  			node_pos := node.position()
@danieldaeschle nevermind. v compiler will complain since i haven't declared the `data` parameter in `walker.inspect` as a mutable voidptr.

![image](https://user-images.githubusercontent.com/7358345/108350915-c5062900-721f-11eb-8643-3eaad4209fb3.png)

2021-02-18 12:17 UTC, nedpals commented on vls/ast.v
>  			node_pos := node.position()
it's a non-issue for vls. since data is a voidptr it can unmutable or mutable

2021-02-18 20:38 UTC, danieldaeschle commented on vls/ast.v
>  			node_pos := node.position()
okay, strange...

2021-02-18 20:39 UTC, merged