vls: better logging for debug
vlang/vls pull request #80
Opened 2021-02-26 14:00 UTC by nedpals

This PR implements the LSP inspector logging for better and easier debugging. Another goal for this PR is to encourage better error reporting. Closes #20.

**NOTE: What you are seeing right now is not final and uses the `log` module in the meantime.**

## Roadmap
- [ ] Create `lsp-log` module
  - [ ] Implement logging methods stated in the `log.Logger` interface
  - [ ] Tests
- [ ] Add `logger` field in `Vls` struct (Uses `log.Log` for now. Will be replaced with `log.Logger`)
- [x] Implement logging inside `send` and `dispatch`
- [x] Use `trace` field from the received initialize params.
- [x] Replace `panic` with `ls.panic` or similar inside option `OrBlock` in methods
- [x] Add `debug` option in CLI
- [ ] Add friendly message when the language server crashes (Implemented but not yet final)

## Stretch Goals
Just goals that are relevant to this PR but not necessary in implementing the feature.

- [ ] Implement way to report issue in Github

2021-02-28 06:49 UTC, nedpals commented
Upon revisiting https://github.com/microsoft/language-server-protocol-inspector, there have been a few quirks to this:

1. The text format is human-readable yet memory consuming and lots of stuff such as response latency feels unnecessary.
2. Turns out the [JSON example found on the log format](https://github.com/microsoft/language-server-protocol-inspector#log-format) does not work anymore and employs a new format that is hidden behind the examples (See [this](https://github.com/microsoft/language-server-protocol-inspector/blob/main/lsp-inspector/src/store/sample.log.json)) and it is just similar to its text format counterpart for the reasons I've stated in number 1.

I'll still gonna use their example since it balances the right stuff and I'll definitely gonna build a new simple LSP inspector for it :laughing: (in another time ofc)

2021-03-04 02:14 UTC, nedpals commented
I have implement the standard LSP log text format support. So far it is working so I'm not gonna make a new inspector anymore. 
![image](https://user-images.githubusercontent.com/7358345/109900500-71d9af00-7cd2-11eb-98ba-ad3ed8f4fe96.png)

2021-03-04 07:06 UTC, danieldaeschle commented
awesome!

2021-03-04 07:13 UTC, danieldaeschle requested changes
pretty good code!

2021-03-04 07:13 UTC, danieldaeschle commented on lsp/log/log.v
> +pub fn (l Log) str() string {
this needed?

2021-03-04 07:13 UTC, danieldaeschle commented on lsp/log/log_test.v
> +	// assert result.timestamp == current_time
Remove

2021-03-04 07:13 UTC, danieldaeschle commented on lsp/log/log_test.v
> +	// assert result.timestamp == current_time
Remove

2021-03-04 07:13 UTC, danieldaeschle commented on lsp/log/log_test.v
> +	// assert result.timestamp == current_time
Remove

2021-03-04 07:13 UTC, danieldaeschle commented on lsp/log/log_test.v
> +	// assert result.timestamp == current_time
Remove

2021-03-04 07:13 UTC, danieldaeschle commented on vls/diagnostics.v
> +fn (mut ls Vls) show_diagnostics(uri lsp.DocumentUri) {
mut?

2021-03-04 07:13 UTC, danieldaeschle commented on vls/general.v
> +	ls.logger.close()
what happens on crash?

2021-03-04 07:13 UTC, danieldaeschle commented on vls/vls.v
> +	logger           log.Log
should we have a interface for this? if it's possible to have different loggers...

2021-03-04 07:13 UTC, danieldaeschle commented
Could you add an instruction how to get that logging screen?

2021-03-04 11:06 UTC, nedpals commented on lsp/log/log.v
> +pub fn (l Log) str() string {
I should file an issue for this. I just added this for now since there is a cgen when generating a `str()` method with strings.Builder

2021-03-04 11:09 UTC, nedpals commented on vls/diagnostics.v
> +fn (mut ls Vls) show_diagnostics(uri lsp.DocumentUri) {
Yep. It should be mutable because the log uses strings.Builder and os.File which are mutable

2021-03-04 11:14 UTC, nedpals commented on vls/general.v
> +	ls.logger.close()
On the event that it won't be executed by `ls.panic(), I'm not sure about it. I'm pretty sure there's a way to detect sudden crashes. I'll find a way for it.

2021-03-05 10:40 UTC, danieldaeschle commented on lsp/log/log.v
> +pub fn (l Log) str() string {
Yes, and add a comment please.

2021-03-08 02:11 UTC, nedpals commented on vls/vls.v
> +	logger           log.Log
I can implement it but custom loggers have to stick to the design of the `lsp.Log`'s methods since they have a different way of logging stuff compared to the traditional info/warn/error log

2021-03-08 02:17 UTC, nedpals commented
> Could you add an instruction how to get that logging screen?

I'll add it on the crash window and to the README

2021-03-08 02:21 UTC, nedpals commented on lsp/log/log.v
> +pub fn (l Log) str() string {
fixed in the latest version of V

2021-03-09 06:21 UTC, nedpals commented on vls/general.v
> +	ls.logger.close()
> I'm pretty sure there's a way to detect sudden crashes. I'll find a way for it.
Turns out there's no way for this to be achieved in the current state of V. I'll just have to leave this for now.

2021-03-09 06:21 UTC, nedpals commented
Ready for review

2021-03-09 07:31 UTC, danieldaeschle commented on lsp/log/log_test.v
> +	time.sleep(320 * time.millisecond)
this needed in a unit test?

2021-03-09 07:33 UTC, danieldaeschle commented
Move image to a sub dir.

2021-03-09 07:34 UTC, danieldaeschle requested changes
Fine! one or two changes and then it can be merged.

2021-03-09 07:39 UTC, nedpals commented on lsp/log/log_test.v
> +	time.sleep(320 * time.millisecond)
Nope. I just removed it now.

2021-03-09 07:41 UTC, nedpals commented
> Move image to a sub dir.

@danieldaeschle  Should I name it `readme_images`? Or is `images` fine already?

2021-03-09 07:43 UTC, danieldaeschle approved these changes

2021-03-09 07:46 UTC, nedpals commented
All is good. I shall merge it now. Thanks @danieldaeschle :smiley:

2021-03-09 07:46 UTC, merged